### ISSUE TITLE
[testing WP5] font-awesome icons are not showing by default

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/jinsy-magazine#14]
@stefan-cotitosu After installing the theme, font-awesome icons are not appearing by default in the feature and team section. Screenshot: http://prntscr.com/lqysov http://prntscr.com/lqysz8

**Comment by stefan-cotitosu** [comment]
@poonam279 This issue is because we upgraded to Font Awesome 5 in Orbit Fox earlier than in Hestia.
Font Awesome 5 didn't work as expected and it was reverted in Hestia theme. We will revert it in Orbit Fox too.

The issue will be fixed on the next release of Orbit Fox. For now it happens in Hestia Lite too. Sections affected by this Font Awesome migration are from Orbit Fox plugin.

Thanks for reporting it 👍
